### PR TITLE
Increase buffer size to 4096 for net_dns_record requests

### PR DESCRIPTION
**Pull request by massyn**
# Example query results
<details>
  <summary>Results</summary>

```
select value from net_dns_record where domain = 'github.com' and type = 'TXT'
```
</details>

### CODE REVIEW

**Comment by massyn** [comment]
Hi @cbruno10 - what is the ETA to get this pull request approved?

**Comment by cbruno10** [comment]
Hey @massyn , sorry for the delayed response. I think instead of increasing the buffer size, we should instead look to retry with TCP if we get a truncated response, similar to how nslookup does it. It's on our radar to implement, but we haven't had a chance yet.

If you're interested in attempting this update in this PR, please let us know and we're happy to help along the way.

One note I'll mention is we currently use a utility `retryHydrate` function (https://github.com/turbot/steampipe-plugin-net/blob/main/net/table_net_dns_record.go#L273), which is defined in https://github.com/turbot/steampipe-plugin-net/blob/main/net/utils.go#L183. So we should continue to use this, but we shouldn't wrap the UDP + TCP attempts in the same `retryHydrate`, since if we know the response is truncated, we don't want to retry the UDP request with each TCP request.

**Comment by cbruno10** [comment]
@massyn In the meantime, as a workaround you can use this branch and build locally wherever you need the plugin in order to override the default buffer size. If you run into other technical issues with this workaround though, please let us know.

**Comment by cbruno10** [comment]
@massyn I'm closing this PR for now, as I'm hesitant to increase the buffer size to 4096 for all requests. I believe the better solution is to implement a proper TCP fallback mechanism if we discover that the UDP request response was truncated as I mentioned in https://github.com/turbot/steampipe-plugin-net/issues/56#issuecomment-1419866875.

This item will be in our backlog, so we may not get to it in the near future. If you'd like to try implementing it, please feel free to do so and we'll be happy to help. Thanks!

**Comment by massyn** [comment]
Hey @cbruno10 - I've got the workaround branch already running.  If this is not getting fixed in the short term, I think the better approach for me will be top stop using this plugin, and revert to using a python script instead, so I can have a reliable data source.

**Comment by cbruno10** [comment]
Hi @massyn , this item is still on our TODO list, but we have some other items in front of it unfortunately. If the workaround branch works is working for you, then the requests should still complete OK; however, I understand if using a local plugin version is not feasible for any reason.

We'll update the original issue once we start working on implementing the backoff solution.

**Pull request closed without merging**
